function love.conf(t)
    t.identity              = nil                   -- Имя папки, в которую LÖVE будет сохранять файлы (строка)
    t.appendidentity        = false                 -- Искать файлы в корневой папке игры перед их поиском в папке сохранений (логическое)
    t.console               = true                  -- Разрешить консольный вывод (boolean, работает только в Windows)
    t.accelerometerjoystick = true                  -- Включить акселерометр на Android и iOS устройствах, представив его в виде джойстика (логическое)
    t.externalstorage       = false                 -- При значении true LÖVE будет сохранять данные на внешнем хранилище Android смартфона (логическое) 
    t.gammacorrect          = false                 -- Включить гамма-коррекцию, если поддерживается системой (логическое)

    t.audio.mixwithsystem   = true                  -- Не останавливать фоновую музыку при открытии LÖVE (логическое, только для Android и iOS)

    t.window.title          = "Назови меня"         -- Заголовок окна (строка)
    t.window.icon           = nil                   -- Путь до файла картинки, которая будет использоваться в качестве иконки окна (строка)
    t.window.width          = 800                   -- Ширина окна (число)
    t.window.height         = 600                   -- Высота окна (число)
    t.window.borderless     = false                 -- Убрать рамки у окна (логическое)
    t.window.resizable      = false                 -- Разрешить пользователю изменять размер окна (логическое)
    t.window.minwidth       = 1                     -- Минимально возможная ширина окна (число)
    t.window.minheight      = 1                     -- Минимально возможная высота окна (число)
    t.window.fullscreen     = false                 -- Включить полноэкранный режим (логическое)
    t.window.fullscreentype = "desktop"             -- Выбор полноэкранного режима "desktop" или "exclusive" (строка)
    t.window.vsync          = 1                     -- Использовать вертикальную синхронизацию (число)
    t.window.msaa           = 0                     -- Степень мультисемплинга (число)
    t.window.display        = 1                     -- Номер монитора, на котором будет показано окно игры (число)
    t.window.highdpi        = false                 -- Включить режим высокой чёткости (логическое, только для Retina дисплеев)
    t.window.x              = nil                   -- Расположение окна на дисплее по X, при значении nil - середина ширины дисплея (число)
    t.window.y              = nil                   -- Расположение окна на дисплее по Y, при значении nil - середина высоты дисплея (число)

    t.modules.audio         = true                  -- Включить модуль audio (логическое)
    t.modules.data          = true                  -- Включить модуль data (логическое)
    t.modules.event         = true                  -- Включить модуль event (логическое)
    t.modules.font          = true                  -- Включить модуль font (логическое)
    t.modules.graphics      = true                  -- Включить модуль graphics (логическое)
    t.modules.image         = true                  -- Включить модуль image (логическое)
    t.modules.joystick      = true                  -- Включить модуль oystick (логическое)
    t.modules.keyboard      = true                  -- Включить модуль keyboard (логическое)
    t.modules.math          = true                  -- Включить модуль math (логическое)
    t.modules.mouse         = true                  -- Включить модуль mouse (логическое)
    t.modules.physics       = true                  -- Включить модуль physics (логическое)
    t.modules.sound         = true                  -- Включить модуль sound (логическое)
    t.modules.system        = true                  -- Включить модуль system (логическое)
    t.modules.thread        = true                  -- Включить модуль thread (логическое)
    t.modules.timer         = true                  -- Включить модуль timer (логическое, при выключении этого модуля deltatime будет всегда 0)
    t.modules.touch         = true                  -- Включить модуль touch (логическое)
    t.modules.video         = true                  -- Включить модуль video (логическое)
    t.modules.window        = true                  -- Включить модуль window (логическое)
end     